import Head from 'next/head'
import Image from 'next/image'
import Articles from '../components/Articles'
import User from '../components/User'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>React Skeleton screen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <header className={styles.header}>
          <h1>React Skeletons</h1>
        </header>
        <div className={styles.content}>
          <Articles />
          <User />
        </div>
       </main>
    </div>
  )
}
